<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';

class Project extends REST_Controller
{

    function __construct()
    {
        // Construct the parent class
        parent::__construct();
        $this->load->model('project_model');
    }

    public function index_get()
    {
        $result = $this->project_model->getProjects();

        $projects['data'] = array();
        foreach($result as $project) {
            $data['id'] = $project->id;
            $data['name'] = $project->name;
            $data['description'] = $project->description;
            $data['created_on'] = $project->created_on;
            array_push($projects['data'], $data);
        }

        $this->set_response($projects, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
    }

    public function id_get($id) {
        $result = $this->project_model->getProject($id);
        $this->set_response($result, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
    }

    public function id_delete($id)
    {
        // $id = (int) $this->get('id');
        // Validate the id.
        if ($id <= 0)
        {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }
        $this->project_model->deleteProject($id);
        $message = [
            'id' => $id,
            'message' => 'Deleted the resource'
        ];
        $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
    }

    public function index_post() {
        if(!empty($this->post('name')) && !empty($this->post('description'))) {
            $data = [
                'name' => $this->post('name'),
                'description' => $this->post('description')
            ];
            $id = $this->project_model->createProject($data);
            $message = [
                'id' => $id, // Automatically generated by the model
                'name' => $this->post('name'),
                'description' => $this->post('description'),
                'message' => 'Added a resource'
            ];
            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }
    }

    public function index_put() {
        if(!empty($this->post('name')) && !empty($this->post('description')) && !empty($this->post('id'))) {
            $data = [
                'id' => $this->post('id'),
                'name' => $this->post('name'),
                'description' => $this->post('description')
            ];
            $this->project_model->updateProject($data);
            $message = [
                'id' => $this->post('id'), // Automatically generated by the model
                'name' => $this->post('name'),
                'description' => $this->post('description'),
                'message' => 'Updated a resource'
            ];
            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }
    }

}